//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace techService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int id { get; set; }
        public System.DateTime beginDate { get; set; }
        public int equipmentId { get; set; }
        public int faultId { get; set; }
        public string Description { get; set; }
        public int clientId { get; set; }
        public int statusId { get; set; }
        public int workerId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual EquipmentsToRepair EquipmentsToRepair { get; set; }
        public virtual Status Status { get; set; }
        public virtual typesOfFault typesOfFault { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
